### ISSUE TITLE
SSL error when Miniflux is trying to read the RSS feed

### ISSUE THREAD

**Issue by EpocDotFr** [kanboard/website#1]
Since a few days, Miniflux is unable to fetch the [RSS feed of the Kanboard website](https://kanboard.net/feed). The console shows this error:

> PicoFeed\Client\Curl cURL error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Also, the feed title is wrong (Miniflux instead of Kanboard)

**Comment by fguillot** [comment]
I fixed the title of the feed but for the SSL error, your curl want to use SSL v3 and it's not available, maybe you have a very old version of curl.

Kanboard is hosted behind Cloudflare and I use their SSL certificate (https://www.ssllabs.com/ssltest/analyze.html?d=kanboard.net&s=104.28.17.221) Only TLS 1.x is activated.

On which operating system do you run Miniflux? What happens if your run `curl -v https://kanboard.net/feed`

**Comment by EpocDotFr** [comment]
My Miniflux instance is hosted on a shared server at OVH, here are some details but I think they are irrevelant.

> Version de PHP : 5.6.20
> PHP SAPI : fpm-fcgi
> Version du système d'exploitation : Linux 3.14.60-grsec-hosting-web-3.14

It seems they have deactivated SSLv3 due to POODLE vulnerability (http://travaux.ovh.net/?do=details&id=11978) but I don't understand why cURL want to use it.

I'll dump you the cURL version this evening with phpinfo.

**Comment by EpocDotFr** [comment]
Here are the cURL informations:

![sans titre](https://cloud.githubusercontent.com/assets/2053431/14964271/b4b6fd60-10a7-11e6-921b-12eef51ae6fa.png)

**Comment by fguillot** [comment]
I don't use Cloudflare anymore but my own SSL certificate. So it should work.
